# Generated by Django 3.0.7 on 2020-07-02 01:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='', help_text='Nombre del juego', max_length=20, unique=True)),
                ('words', models.TextField(default='', help_text='Palabras del juego')),
                ('hunts', models.TextField(default='', help_text='Pistas del juego')),
            ],
            options={
                'verbose_name_plural': 'Tables',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('time', models.PositiveIntegerField(help_text='Tiempo del juego en segundos')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='soupApp.Table')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Games',
            },
        ),
    ]
