# Generated by Django 3.0.6 on 2020-05-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soupApp', '0003_auto_20200528_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='hunts',
            field=models.TextField(default='', help_text='Pistas del juego'),
        ),
        migrations.AddField(
            model_name='table',
            name='words',
            field=models.TextField(default='', help_text='Palabras del juego'),
        ),
    ]
