# Generated by Django 3.0.7 on 2020-06-11 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soupApp', '0004_auto_20200529_0905'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'verbose_name_plural': 'Games'},
        ),
    ]
