# Generated by Django 3.0.7 on 2020-06-11 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soupApp', '0005_auto_20200611_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='time',
            field=models.PositiveIntegerField(help_text='Tiempo del juego en segundos'),
        ),
    ]
