# Generated by Django 3.0.7 on 2020-06-24 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soupApp', '0006_auto_20200611_1629'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tutorial',
        ),
    ]
